"""
classes and utility functions related to
TextExample data
"""

from dataclasses import dataclass
from typing import List, Optional

import numpy as np


@dataclass
class Label:
    label: int
    score: float


@dataclass
class TextExample:
    text: str
    id: str
    embedding: Optional[np.ndarray] = None
    cluster_labels: Optional[List[Label]] = None  # labels assigned by a Labeller


@dataclass
class LabelledTextExample(TextExample):
    assigned_labels: Optional[List[Label]] = None  # e.g., ground truth labels, predicted labels
    candidate_labels: Optional[List[Label]] = None  # candidate labels/scores generated by comparing cluster labels to assigned labels


def read_test_labelled_topics() -> List[LabelledTextExample]:
    """
    convert test_data/labelled_topics.csv to a list of text examples
    """
    with open("test_data/labelled_topics.csv", "r") as f:
        data = f.readlines()
    labelled_examples = []
    for i, row in enumerate(data[1:]):
        label, text = row.split(",")
        text = text.strip()
        labelled_examples.append(LabelledTextExample(
            text=text,
            id=str(i),
            assigned_labels=[Label(label, 1.0)]
        ))
    return labelled_examples


def sorted_cluster_labels(examples: List[TextExample]) -> List[str]:
    """
    returns a sorted list of all unique cluster labels in examples
    """
    label_list = [example.cluster_labels for example in examples if example]
    if len(label_list) == 0:
        return []
    return sorted(set([label.label for labels in label_list for label in labels]))


def sorted_assigned_labels(examples: List[LabelledTextExample]) -> List[str]:
    """
    returns a sorted list of all unique cluster labels in examples
    """
    label_list = [example.assigned_labels for example in examples if example]
    if len(label_list) == 0:
        return []
    return sorted(set([label.label for labels in label_list for label in labels]))
